### ISSUE TITLE
Terminator.img not found

### ISSUE THREAD

**Issue by goldcove** [furrtek/portapack-havoc#1]
Greetings, I've cam across this error while compiling the havoc portapack:
```
[ 93%] Generating baseband.img
cat: terminator.img: Not found
firmware/baseband/CMakeFiles/baseband.dir/build.make:75: recipe for target 'firmware/baseband/baseband.img' failed
```
Since I didn't want to debug the makefiles I just copied the file to workig dir (build/firmware/baseband) as a workaround :-D (yeah, I'm lazy...)

**Comment by furrtek** [comment]
Hello.
Bad rule in .gitignore, terminator.img is there now ;) Thanks.
