### ISSUE TITLE
SD Card Utility

### ISSUE THREAD

**Issue by gh0stshell** [furrtek/portapack-havoc#10]
I used the built in utility to format the card and now I get no filesystem. What file format does the card need to be in, could not easily find this out.

**Comment by gh0stshell** [comment]
Also when I record using capture or record through an audio received when I go to soundboard and try to place something I recorded it says no files in /wav/

**Comment by furrtek** [comment]
There's no utility to format the SD card. The "Wipe SD card" utility simply clears the first 32MBs to 0, as indicated on the warning screen. Only useful as a delete in emergency situations.
Soundboard loads files from the /wav directory. Recorded audio is placed at root. I'll add a folder selection screen soon.

**Comment by gh0stshell** [comment]
what about the format the card should be in?

**Comment by furrtek** [comment]
FAT32
