### ISSUE TITLE
Portapack crash and reboot on "Receivers -> ADS-B"

### ISSUE THREAD

**Issue by F4GEV** [furrtek/portapack-havoc#101]
All is in the description
All the rest of tested functionnalities works

thanks
Laurent

**Comment by F4GEV** [comment]
Precision,
i don't have generate the map BIN file !

**Comment by F4GEV** [comment]
Works with world_map files added to SDCard

Stay a bug :-)

**Comment by furrtek** [comment]
Can't reproduce for now. Did you have to go in the map view for it to crash ?

**Comment by F4GEV** [comment]
Can't reproduce too. (removed files from SD Card)
No the crash gone when you clic on ADS-B: Planes menu item.

Close this issue with this release and i'm trying to reproduce for the next

@+ et Merci

**Comment by F4GEV** [comment]
Find  !!! Power limitation from one USB port with only this menu !!!


????? Strange   ????

Solved "sorry"
