### ISSUE TITLE
Frequency manager crash after KDR444 category

### ISSUE THREAD

**Issue by furrtek** [furrtek/portapack-havoc#103]
Freeze when selecting a category above KDR444 (default frequency lists).

**Comment by djecom1** [comment]
For information, I removed KDR444 from the list, and it freeze too.

**Comment by ImDroided** [comment]
Remove the next in line from there and see what happens.

**Comment by djecom1** [comment]
A short video showing the crash : 
[https://youtu.be/0QgO-v36feQ](url)

**Comment by furrtek** [comment]
Should be fixed in 34b99042efe62825f986c4f4845635766a8c7365.
I believe the crash was caused by RAM overflow ? Entries per file are limited to 50 until I can figure out more.

**Comment by djecom1** [comment]
Fixed.
Merci !!
