### ISSUE TITLE
ADSB Map is broken now

### ISSUE THREAD

**Issue by ImDroided** [furrtek/portapack-havoc#106]
When trying to load the map I get no world_map.bin file in /ADSB/ directory. I have the file on the SD card and it shows up in the file manager.

**Comment by ImDroided** [comment]
same in transmit also

**Comment by furrtek** [comment]
Fixed in 04c5b4d6070c72c693cb6f8d79e95c52c5faa7cd. Thanks :)

**Comment by ImDroided** [comment]
Sweet. I will test later today and close this

**Comment by KR0SIV** [comment]
This is broken again it would appear, or at least the sdcard/adsb folder contains a .jpg file rather than a bin. At any rate it triggers the error, I renamed the ext but until more aircraft come into view i won't know for sure if it's loading it.

**Comment by furrtek** [comment]
Did you follow https://github.com/furrtek/portapack-havoc/blob/master/sdcard/README.md ?

**Comment by KR0SIV** [comment]
no, I'm sorry.. I feel like a damn fool now should've RTFM

**Comment by furrtek** [comment]
No problem, information is spread across a lot of (too many) pages :)
