### ISSUE TITLE
Replay Option

### ISSUE THREAD

**Issue by gh0stshell** [furrtek/portapack-havoc#11]
When I go into the reply menu item and select record there is no indication that anything is happening and the unit freezes and I have to reset it. After selecting record I try selecting stop and nothing happens.

**Comment by furrtek** [comment]
Disabled replay menu item for now, not done yet.

**Comment by gh0stshell** [comment]
Just a suggestion but maybe have it show the screen that the other disabled options have so people donet try using it

**Comment by furrtek** [comment]
Done :)

**Comment by gh0stshell** [comment]
Minor issue, when you go to Capture it shows not implemented, when you go to reply it opens capture(looks like the reply screen) if you could fix this real quick I would highly appreciate it.
