### ISSUE TITLE
Old M2K2 identifier

### ISSUE THREAD

**Issue by F4GEV** [furrtek/portapack-havoc#112]
Hello Mr,
i have try the radiosonde decoder with an old M2K2 (yes i have some M2K2 :-) )

His identifier is 0x648F23. your only identify M2K2 with 0x648F20 in your prog

@+
F4GEV

**Comment by F4GEV** [comment]
Correction !!! I go my M2K2 outside !!
the M2K2 send when GPS position is determined
0x648F23 when not dermined 

@+

**Comment by furrtek** [comment]
Added the identifier in 17b238f3a8a06ef10c7f9cebd435f7e82ec8464c, will try disabling the GPS module on a M10 to see if it also transmits ...23. Thanks :)

**Comment by F4GEV** [comment]
Simple : plug the power supply to your M10, there is no backup battery for GPS.
the GPS take few minutes to lock with GPS (TTFF procedure)

Have fun
Laurent
