### ISSUE TITLE
Periodic ticks in soundboard

### ISSUE THREAD

**Issue by furrtek** [furrtek/portapack-havoc#12]
Period related to wav file samplerate.
Caused by WAVFileReader::read being slow ?
Wasn't happening when just using a simple File object.

**Comment by djpadbit** [comment]
I did some testing with a simple app (just a button) and WAVFileReader::read didn't produce ticks but did in the soundboard, weird. If using a simple File object didn't produce ticks this probably mean that WAVFileReader::read takes longer than a File object ? You should probably reuse a File object then ? I don't know, anyways hopes this helped :D (i probably just said some useless stuff)

**Comment by furrtek** [comment]
Thanks @djpadbit, WAVFileReader::read is directly inherited from File::read so it should take the same amount of time. Thought it was because of the progressbar update but it wasn't.
I reduced the FIFO refill size from 1024 bytes to 512 (smaller but more frequent reads) in 446efa8 and the ticks seem to have disappeared ?

**Comment by djpadbit** [comment]
The ticks seem to indeed have disappered. Thanks as always for making such an awesome firmware.
