### ISSUE TITLE
adsb_map build

### ISSUE THREAD

**Issue by KC5CQW** [furrtek/portapack-havoc#122]
Syntax error (str) of last line in python shell:
print str(y) + '/' + str(im.size[1]) + '\r',

d517bc3

Python 3.7.0a2 (v3.7.0a2:f7ac4fe, Oct 17 2017, 17:06:29) [MSC v.1900 64 bit (AMD64)] on win32

**Comment by furrtek** [comment]
Fixed in 196518457f61e820849ecd48a7b2c040fee3b463, thanks.
