### ISSUE TITLE
Suggestion: Adding Wifi Deauther

### ISSUE THREAD

**Issue by chimera234** [furrtek/portapack-havoc#125]
Hello,
Nice addon for exisiting Jammer would be a Deauther feature, details are available at:

https://github.com/spacehuhn/esp8266_deauther

The deauth attack will, if the connection is vulnerable, disconnect the devices from the network. Because the attack is running constantly, the devices will be disconnected again and again. Depending on the network, that can either block a connection or slow it down

Thanks

**Comment by furrtek** [comment]
Hey,
The ESP8266 makes it seem simple but 802.11 is tough stuff, certainly too tough for the Portapack all alone.

**Comment by Misfitsman805** [comment]
Could you not just use the jammer feature and inject tons of noise onto the wifi 2.4ghz band?
