### ISSUE TITLE
Feature request: Allow Amp toggle for ADS-B Rx

### ISSUE THREAD

**Issue by unixpunk** [furrtek/portapack-havoc#126]
For some reason my HackRf (with/without PortaPack) sees no ADS-B signals when the Amp is enabled regardless of the combination of gain settings used.  Only until I disabled the Amp in the ui_adsb_rx.cpp was I able to get it to work and see planes on the list.  Not sure if anyone else has this issue or if something is up with my hw, but the ability to toggle would help out, even in cases of nearby high-powered transmitters that, without a BP/Notch filter, will always overload the internal amp.  Thanks!

**Comment by furrtek** [comment]
Will have to unify the reception settings in a simple widget. Will do soon :)

**Comment by unixpunk** [comment]
Ah ya, that would be good, same options on each Rx.  Thanks!

**Comment by ImDroided** [comment]
I agree. I wonder if there is a easy way to do this. It would he awesome if we had a separate screen with a waterfall that would open for us to fine tune the received signal to get better results.

**Comment by furrtek** [comment]
Added RF amp setting in 65a99bbe5ada43ad912986c51fd69fc3b4f17436

**Comment by unixpunk** [comment]
Thank you, sir!  Will compile and play tonight!

**Comment by unixpunk** [comment]
Works as intended.  In ADS-B Rx I can now toggle the Amp and see that it does take effect.  Thanks!

**Comment by djecom1** [comment]
@unixpunk I think your LNA is out of order. I had the same issue and I fixed it. You juste have to change the LNA with this method :
http://www.t4f.org/articles/repairing-the-hackrf/

**Comment by unixpunk** [comment]
Thanks, ya I found that site as well and confirmed as much with his suggested testing.  I already have the new part just haven't put it on yet.  I believe GreatScott might also repair them too, though I have sought out a quote at this time.
