### ISSUE TITLE
SDCARD - Add swissphone POCSAG frequencies

### ISSUE THREAD

**Issue by cnyxradio** [furrtek/portapack-havoc#140]
Swisscom is the Swiss equivalent of the French POCSAG service provider called E-Message.

Here are frequencies :
147.300 MHz
147.325 MHz
147.375 MHz
147.400 MHz
169.700 MHz

**Comment by fantuz** [comment]
Correct, validated (months i listen these 5fqs) but the name is Swissphone,
not Swisscom :) German BOS equivalent.

**Comment by furrtek** [comment]
Thanks, added in 951d3d88604b61dc9f8744e48a86f92b8f8260cc

**Comment by Pyr3x** [comment]
How about some American frequencies? Give us some love!
