### ISSUE TITLE
Add ctcss tone in soundboard

### ISSUE THREAD

**Issue by F0GPI** [furrtek/portapack-havoc#142]
Hi furtekk, 
It’s possible to integer the ctcss module in soundboard app in the future fix ?

**Comment by furrtek** [comment]
Hello, the tone key module was temporarily removed from the soundboard because of a RAM issue.
I'm still trying to figure out why this happens.

**Comment by furrtek** [comment]
Added back in 96828262d712b08abb675b7c4424fec47d8ffb93 :)
