### ISSUE TITLE
NOT ISSUE:  Would anyone else like to see a HAVOC facebook group to discuss success/fails on their attempts?

### ISSUE THREAD

**Issue by chudgoo** [furrtek/portapack-havoc#148]
Seems like the GitHub issue board is becoming the trial and error zone. 
Would anyone else like to see another forum (that doesn't clog up Furrtek's inbox unnecessarily) while we all work out our smaller problems?
I'll start one and hope to see some of you there with your problems, solutions, work-arounds, etc.
The tool is amazing. The capabilities are amazing. The 'getting shit to do what you intend' is a crap shoot sometimes and help is always out there... Just not sure the GitHub "Issues" page is the place for a lot of it.
Delete if you think I'm out of line btw...

**Comment by furrtek** [comment]
Maybe link to it so I can share it ? I can't find it from Facebook's search engine.
I think it's a nice idea, and if an issue or an idea needs tracking, I can always open an issue here to add technical details about progress.

**Comment by unixpunk** [comment]
I'd join and help out where I can, as long as its not on facebook, I'd suggest something else like groups.io, etc though.

**Comment by ImDroided** [comment]
I'd join. That's githubs one flaw... No discussion area.

**Comment by azzeloof** [comment]
How about Slack?
(Also, Hi. I haven't contributed at all yet but I'd like to!)

**Comment by chudgoo** [comment]
https://www.facebook.com/groups/177623356165819/

**Comment by fantuz** [comment]
hi, such facebook page is not available for me. what about permissions? my fb address is different from my github one.

i see that groups.io was alsochoosen by sdrangel project for thesame purpose: shall we also move there as proposed by @unixpunk ?

**Comment by ImDroided** [comment]
Furrtek you should make the page wherever it may reside so you can remain
in control I'd hate to see us get locked out due to a random person
abandoning the page.

**Comment by chudgoo** [comment]
I only suggested facebook because it's becoming very ubiquitous.
As for abandoning the page, aside from creating it, I had no intention of
playing over zealous moderator or anything... or shutting it down for any
reason,
I just want to talk shop in a members-only, private forum with other
mischievous types and keep the shop talk off the github page. (which I
agree REALLY does need a forum feature)

**Comment by xerospawn** [comment]
The facebook link says page is not viewable at this time.

**Comment by chudgoo** [comment]
Ugh. My mistake... it was set to secret group. It’s public now.

**Comment by ImDroided** [comment]
Chudgoo..... I only mentioned that because of a situation I am currently in. I use to use a piece of software and I created a group discussion for it. Fast forward a few years and I dont use said piece of software anymore but the group is still active and I have no was of passing the group to someone else to take care of. I still have to log in every so often to do things that I now dont want to do.

**Comment by furrtek** [comment]
Joined the FB group (Frna... that's my ROT13'd name).

**Comment by h4waii** [comment]
Why not Groups.io as previously mentioned, or Slack, Discord, Telegram, even Reddit? They're all much more "open" than Facebook yet still allow users to remain fairly anonymous.

**Comment by fantuz** [comment]
hello @h4waii come join the group on FB, anyway nothing much is happening (we're less than 20 so far)
