### ISSUE TITLE
Required dependancy missing from build guide

### ISSUE THREAD

**Issue by ethan4** [furrtek/portapack-havoc#155]
Built yesterday on a fresh install of Ubuntu 16.04.3 LTS and build failed as python wasn't installed.

Not sure if this is expected or just me, but guide might need updating.

**Comment by ImDroided** [comment]
Its pretty much expected. If you run linux you need python they kinda go hand and hand. Was that the only issue?

**Comment by ethan4** [comment]
Yep, everything else went swimmingly. :)
