### ISSUE TITLE
Unable to erase SD card from Utilities menu

### ISSUE THREAD

**Issue by ethan4** [furrtek/portapack-havoc#156]
Tried this a couple of times with an 8GB card with files already on it (FAT filesystem) and it just hung each time, restarting and checking File Explorer showed files still present.

**Comment by furrtek** [comment]
Should be fixed in 57c759627d60b3716f0dafc150d622423b9eafe5. Now only the FAT is erased.

**Comment by unixpunk** [comment]
Confirmed.  Took less than 10 seconds to wipe the partition table from a 16gb card with ~500mb used.  Confirmed no partition on PC and I created the partition again exactly as it was and all data remained and showed up again.  Thanks!

**Comment by furrtek** [comment]
Thanks for the thorough test @unixpunk :)
