### ISSUE TITLE
Capture bandwith always fixed at +/-200k

### ISSUE THREAD

**Issue by chimera234** [furrtek/portapack-havoc#157]
Hello,
As far as I remember in previous versions the channel bandwith in the capture feature got set according to the setting in the audio receiver, but looks like this is not the case anymore.

How can I change the channel bandwith in the capture feature?
I am currently unable to change it, it´s always fixed at +/-200k. But I need to change it for proper recordings.

Thanks
Chimera

**Comment by furrtek** [comment]
Hey,

The audio bandwidth does change depending on the receiver mode you're in, but I believe the I/Q capture bandwidth has always been +/-250k.
I read Sharebrained original code again: sampling_rate is set at 4MHz and the data is decimated by 4 then by 2, so 4M/4/2 = 500k.

It would be possible to add a setting for a few steps down (500k, 250k, 100k, 50k, 25k, 12.5k ?). Should I add that ?

**Comment by ImDroided** [comment]
That could be useful.

**Comment by chimera234** [comment]
That would be really a great feature.

Thanks so much!!

**Comment by furrtek** [comment]
In 7fd987a2b4ca2b746b2ed774810e1725ac8c1f38, steps are 500k, 250k, 100k, 50k and 25k.
The value is written in the .TXT file, and is loaded automatically during Replay like the frequency.

**Comment by chimera234** [comment]
works,thanks
