### ISSUE TITLE
Microphone TX - Mic is not working

### ISSUE THREAD

**Issue by chimera234** [furrtek/portapack-havoc#158]
Hello,

Just wanted to use microphone TX feature and figured out that Mic is not working. Tested with 3 different Mic´s none of them is working - green volume bar is not moving. Tried to use it with different mic gains, no luck still not working.

Does the microphone TX feature work for anybody else?
Thanks for let me know

Chimera

**Comment by jboone** [comment]
Hi @chimera234. Are you using a smartphone-type headset? The PortaPack connector is compatible with most smartphone headsets, and uses a four-conductor TRRS connector. You can read [more on the PortaPack wiki](https://github.com/sharebrained/portapack-hackrf/wiki/Hardware).

**Comment by chimera234** [comment]
Yes, I tried with smartphone headset, also checked with a single mic but no success. 
As far as I remember it worked some time ago before I updated, thats why I wanted to know if someone else has same issue.

**Comment by furrtek** [comment]
Have you seen #123 ?

**Comment by chimera234** [comment]
Thanks. In my case even after exiting the app mic does not work.

**Comment by jboone** [comment]
@chimera234 Which version or git commit hash of firmware are you using? And what is the version number on the front face of your PortaPack?

**Comment by chimera234** [comment]
Works now as described - I misunderstood "exiting the app" - I always reset the HF and tried again, of course without success. Now when starting the mic TX app, I simply exit via the "go back" arrow and enter again and voila mic TX app works :)  Thanks a lot

**Comment by furrtek** [comment]
Should be fixed in 57c759627d60b3716f0dafc150d622423b9eafe5.

**Comment by chimera234** [comment]
works for me :) Thanks a lot
