### ISSUE TITLE
Add DFS jammer

### ISSUE THREAD

**Issue by furrtek** [furrtek/portapack-havoc#165]
Add "fake radar" jammer to disable all DFS AP channels.

**Comment by chimera234** [comment]
When introducing fake radar, APś/Router will then switch to standard channels, so most likely users will not recognize a problem. Or do you plan to combine this with the existing jammer features to run this option in parallel?

Thanks for let me know
Chimera

**Comment by silascutler** [comment]
Assuming this DFS == Dynamic Frequency Selection (DFS), which is related to https://community.arubanetworks.com/t5/Controller-Based-WLANs/What-is-Dynamic-Frequency-Selection-DFS-How-to-Enable-it-What/ta-p/179170
