### ISSUE TITLE
A simple signal detector 

### ISSUE THREAD

**Issue by tibas21** [furrtek/portapack-havoc#169]
Hello ! 
Is it possible to add a simple signal detector like the lawmate RD10.
It easy to use. It detect all signal with to 2levels of sensibility and it measures the the strengt of the signal.
More explications here:

https://www.lawmate-technology.com/lawmate-rd-10-bug-and-hidden-camera-detector/

If we want somethings better, it exist the Raksa idet. A sort of Close call technologie, but which could determinate the type of the frenquency. I invite You to see more about that, i think you Will love it.

**Comment by furrtek** [comment]
Hello.
So you're basically suggesting the Close call app but wide band ?
