### ISSUE TITLE
Bug? Screen blacks out after starting a few things

### ISSUE THREAD

**Issue by ImDroided** [furrtek/portapack-havoc#175]
Ok so under the Keyfob, adsb transmit, jammer... pretty much anything with a start button the screen blacks out upon hitting start. Is this a bug?

**Comment by furrtek** [comment]
Can't reproduce, did you build from source recently ?

**Comment by unixpunk** [comment]
I don't have this issue.  Mine is Git hash 2d3a631.  arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2017-q4-major) 7.2.1 20170904 (release)

I'll pull/flash the latest now and test that.

**Comment by ImDroided** [comment]
Ill rebuild and test again.

**Comment by ImDroided** [comment]
rebuilt and still doing it. built from my desktop this time. upon clicking the srart button the screen goes black until I hit a button then it comes back.

**Comment by furrtek** [comment]
Don't you have stealth mode enabled (mask icon on the top bar) ?

**Comment by ImDroided** [comment]
Well don't I feel like a dumb ass. I don't know how that got enabled.
