### ISSUE TITLE
Sd card

### ISSUE THREAD

**Issue by kevtheskin** [furrtek/portapack-havoc#177]
Can some one please tell me how to create the folders in the sd card for Adsb. I wiped the card within portapack and now I cannot see card or mount card in Linux or windows?

Thanks Kev

**Comment by furrtek** [comment]
As the confirmation message said: the FAT was wiped and so the OS explorers can't guess what filesystem the card uses now. This is done on purpose to make the card appear corrupt and avoid curious people digging into it in case of emergency. It's NOT a formatting tool.

You need to format it with either a special tool in Windows or mkfs.vfat in Linux.

**Comment by kevtheskin** [comment]
Thanks for info. Kev

**Comment by unixpunk** [comment]
If the card was already in working order and you just used this option, then you still have your data, you just need to manually recreate the partition yourself in fdisk, parted or partman.  As long as you create it on the same starting and ending sectors, then data will show up again fine.  HTH
