### ISSUE TITLE
Add PL subtones 

### ISSUE THREAD

**Issue by F0GPI** [furrtek/portapack-havoc#180]
Hi, 
It is possible to add the pl subtones on audio receptor (decoding)and transmitter modes?
Like the ctcss but the pl subtones is mostly used on professional pmr. 
Thanks.

**Comment by kevtheskin** [comment]
Hi F0GPI
I think PL tones and ctcss are the same . Motorola call them PL tones . see https://en.wikipedia.org/wiki/Private_line .

Cheers 73s MM0KJG

**Comment by furrtek** [comment]
Hello,
They're already there. See the two characters at the end of the tone designator.

**Comment by F0GPI** [comment]
Ok ctcss and PL is the same. 
I’m confused for this noob error.
But another coding tone squelch named tone on most pmr /ham radios, it’s this coding Squelch who said. It si possible to add this mod for decoding and encoding?

**Comment by furrtek** [comment]
Are you talking about DCS ?

**Comment by F0GPI** [comment]
No not dcs. 
Thanks for the reply. 
The problem is solved. 
I understand the two caracters are the code of the tone and the two Numbers are the ctcss code. 
I close this issue.
