### ISSUE TITLE
Any new updates

### ISSUE THREAD

**Issue by kevtheskin** [furrtek/portapack-havoc#193]
Hello there,
Any new updates/addons coming

Cheers Kev

**Comment by RED29** [comment]
I had the same question... There a lot of receivers that are on hold..

Cheers!
RED

**Comment by jboone** [comment]
I understand that @furrtek is busy with other things now. If and when he has time to work on HAVOC, I imagine you will see the updates here in the repository. Please see this comment for more on @furrtek's status: https://github.com/furrtek/portapack-havoc/issues/147#issuecomment-407638044

**Comment by RED29** [comment]
@jboone ok thanks. I didn’t know about his comment. Maybe @furrtek is interested in setting up a Patreon account. I would really like to support him montly, and I think a lot other people too!

**Comment by mwarchut** [comment]
I'd second the supporting him.. Making it worth his time to move forward..

**Comment by furrtek** [comment]
Replied in https://github.com/furrtek/portapack-havoc/issues/147

**Comment by RED29** [comment]
Same for me @furrtek thanks for all your work!

**Comment by unixpunk** [comment]
+1 Thanks for all your work!

**Comment by furrtek** [comment]
Don't make this sound like it's definitive, it's not ! :p
I just started being interested in Zigbee.

**Comment by mamogodi** [comment]
Check the book Inside Radio:An attack and defense guide. It deals on zigbee in one of the chapters
