### ISSUE TITLE
Change time and Date

### ISSUE THREAD

**Issue by MaxRomDatastorm** [furrtek/portapack-havoc#198]
hello
Please someone can suggest me the way for change the time and date ?
thank you in advance

**Comment by ImDroided** [comment]
Isn't this done in the settings menu? I'm at work now so I can't check bit
pretty sure that is in there somewhere

**Comment by furrtek** [comment]
Hello,
See main menu > Settings > Date/Time

**Comment by MaxRomDatastorm** [comment]
Hello, Thank you for the reply
yes I've seen the menù in which there are the possibility to change the data & Time, but the problem is that do not appear any numeric keyboard for insert or change that.
when I highlight a numerical field no numerical grid appear.
Thank you

**Comment by furrtek** [comment]
Use the jog wheel when the fields are highlighted.

**Comment by MaxRomDatastorm** [comment]
Revolver. Mechanical problem on the round pas. Thanx and Apologize
