### ISSUE TITLE
SD Card RAW After Using Wipe Tool

### ISSUE THREAD

**Issue by gh0stshell** [furrtek/portapack-havoc#21]
Once I used the wipe tool it wiped the whole card, deleted the partition and put it into a RAW format, once this happened the device would not see the card and I had to use a computer to reformat the card so I could use it again, that was why I was asking about the format it wanted in my other ticket.

**Comment by furrtek** [comment]
What do you want to know ? Why did you make a new ticket ?
I already wrote that wipe != format. Wipe = clear the card to make it unreadable in emergency situations. Format it back to what it was originally (FAT32).

**Comment by gh0stshell** [comment]
Yes you already told me the format, I opened a new ticket because I did not know or see anything about it suppose to be an emergency full wipe, you only mentioned it wipes the first 32mb of the card or at least thats what the prompt says. I would have no opened a ticket if I knew it was suppose to do this.

**Comment by gh0stshell** [comment]
I do not see anything on this page about the wipe tool or it being an emergency all wipe, would have not opened a ticket if this was known

https://github.com/furrtek/portapack-havoc

**Comment by gh0stshell** [comment]
The confirm message is misleading if it removes the data and partition of the card

**Comment by furrtek** [comment]
Will make that clearer, even if "Wipe first 32MB of SD card" pretty much tells what will happen.

**Comment by gh0stshell** [comment]
This to me does not mean it will format the entire card to RAW, wipe can mean different things to different people

**Comment by gh0stshell** [comment]
You can change the message to say Format Card or not, I would just suggest putting something on the page you call your wiki, I looked their first before opening a ticket and did not see anything therefore I though I found an issues with that app

**Comment by furrtek** [comment]
It doesn't format the card...
