### ISSUE TITLE
Impossible to Return Main from ADS-B transmit

### ISSUE THREAD

**Issue by Giorgiofox** [furrtek/portapack-havoc#22]
If you enter in ADS-B transmit from "Code Transmitter" is impossible to return back using keys: is possible only using a pen with touchscreen. If "left" is pressed like other screens, focus go to START.

Obviously I never used it to transmit.

**Comment by furrtek** [comment]
Unfortunate lock due to focus guessing. Will either have to change the guesser's code or move some widgets around.

**Comment by furrtek** [comment]
Using TXView widget now. You should be able to reach the return button.
