### ISSUE TITLE
What is LGE Tool included in the new firmware?

### ISSUE THREAD

**Issue by decadenzio** [furrtek/portapack-havoc#230]
I just can't find the info in the wiki or somewhere else.
I found this page on wikipedia about Laser Guided Energy, kind of a new weaponry system?

https://en.wikipedia.org/wiki/Electrolaser

**Comment by furrtek** [comment]
LGE is a chain of laser tag centers in France.

**Comment by xvostikk** [comment]
> LGE is a chain of laser tag centers in France.

Can you explain more? I am testing now the HackRF with Portapack and it is really difficult to understand how i can use this Transmitter.
Thank you in advance.

**Comment by furrtek** [comment]
It's completely useless if you're not located in or near an LGE laser tag center.
If by any luck you are, then you get pretty much do what you want: spoof hits, change player and team names, start and terminate the session...

**Comment by xvostikk** [comment]
That's why the description of the tool is really necessary. For example in Germany we have not these centers but we use HAVOC. ;)

**Comment by furrtek** [comment]
I mentionned that in the previous reply.
