### ISSUE TITLE
help

### ISSUE THREAD

**Issue by garik7777** [furrtek/portapack-havoc#234]
Hello,can You help me to install the firmware havoc,what am I doing still white background white screen https://youtu.be/LYgLdHF_Jhw
could you tell me that not so do ? hackrf one 2014 ,portapack 2017

**Comment by jboone** [comment]
I watched your video. It looks like you are doing everything correctly. Please try the PortaPack released firmware. Also, try the HackRF firmware with PC software. If these do not work, you may have bad hardware. Please contact the store where you bought the PortaPack and get a replacement.
