### ISSUE TITLE
SSTV directory in microSD should be named "sstv"

### ISSUE THREAD

**Issue by yadox666** [furrtek/portapack-havoc#235]
First of all. Really have to thank you for your nice work!

We were testing sstv TX function and it was not finding the bmp images that should be in the SD card. We copied the github directory to the microSD before. After a while, we noticed revising the code that it was hardcoded "sstv" named directory. After renaming it to lowercase it worked!

**Comment by furrtek** [comment]
Hello and thanks for the report.
I'll either fix the documentation or make the directory naming case-insensitive soon :)

**Comment by yadox666** [comment]
Just wanting to help! Just have to thank! If I can help you in anything, don't hesitate to contact me!
