### ISSUE TITLE
Replay does not work - Get Havoc Bin File

### ISSUE THREAD

**Issue by witc** [furrtek/portapack-havoc#236]
Hi,

I am windows user. I have just downloaded Havoc Bin file from year 2018 - I tried Capture and Replay functions, but it looks like the replay function always replay only CW even the Modulation was recorded (I tried OOK and FSK). 
Can anyone help me how to compile the source code on windows to get the newest Bin file for upgrading my Portapack?
Or can anyone share the Bin file with me?

Thank you very much, witc68.

**Comment by sliceratwork** [comment]
Hope this helps. It's compiled from the latest code.
[portapack-h1-havoc.zip](https://github.com/furrtek/portapack-havoc/files/3108187/portapack-h1-havoc.zip)
