### ISSUE TITLE
Cant re-flash

### ISSUE THREAD

**Issue by kevtheskin** [furrtek/portapack-havoc#239]
Hello there, Can someone please help re-flash my portapack. I flashed it with Unix-punk fw and now stuck with just a black screen. Please any help much appreciated. Thanks Kev

**Comment by furrtek** [comment]
Whatever happens you should still be able to flash it by following the regular procedure with dfu-util.

**Comment by kevtheskin** [comment]
Hello furrtek, Thanks for getting back to me . I got it working again. Had to dust down my linux laptop. Hope you are well and maybe have some time to write some goodies for the havoc bin. Cheers Kev
