### ISSUE TITLE
C16 file format complex, float...?

### ISSUE THREAD

**Issue by VeloVolo** [furrtek/portapack-havoc#246]
What data contain these files? complex, float..?
Could not find any information about these files.
May be someone could advise how to open these files in GNU Radio?

**Comment by furrtek** [comment]
C16 means Complex 16-bit. It's a stream of 16-bit integer pairs for I and Q.
Try the "ishort to complex" block in GRC.

**Comment by VeloVolo** [comment]
Thank You! That is i was looking for!

**Comment by TeleportingKitten** [comment]
Can I decrypt the C16 file format?  Man code is definitely what I lack in. I put the file in a hex edit but it shows nonsense because it's encrypted.

**Comment by furrtek** [comment]
It's not encrypted. Why would it be ?
You're seeing pairs of signed 16-bit values as stated above.

**Comment by furrtek** [comment]
Info added to https://github.com/furrtek/portapack-havoc/wiki/Capture
