### ISSUE TITLE
A place to talk

### ISSUE THREAD

**Issue by jr-k** [furrtek/portapack-havoc#25]
Hello,

First this is not an issue but a request. Thanks for this very cool firmware. I would like to help and make some PR. Is there any slack/irc where we can all interact about this repository ? (I would like to add some features for sigfox/lora networks)

Thanks again.

**Comment by furrtek** [comment]
Hello,
Thanks for the kind words. There's #portapack on irc.freenode.org already, but maybe we should register another channel ?

**Comment by jr-k** [comment]
Maybe we should start a #portapack-havoc on irc.freenode.org ? 
Don't forget to reference the channel you'll choose in readme.md.

**Comment by furrtek** [comment]
@Sharebrained is ok with using #portapack

**Comment by jr-k** [comment]
Ok let's use it then.
