### ISSUE TITLE
error no file system??

### ISSUE THREAD

**Issue by TeleportingKitten** [furrtek/portapack-havoc#255]
I'm getting an error when I click the little red R icon when using the Capture, it's saying error at the top left and telling me I have no File system? I click OK and it brings me back to the Hack RF one capturing screen. It's definitely capturing because I see the spectrum, but am I missing files? I have a 64gb SD card inserted.

**Comment by furrtek** [comment]
Is the card FAT32 formatted ? Is the capture file present and >0 in size ? Maybe a block size problem.

**Comment by TeleportingKitten** [comment]
I was actually trying to delete the post if I could haha, I'm new to github, I got it working. Basically it needs to be a FAT format or FAT32. I have another problem though, I'm not able to generate the world_map.bin file. Do I just dubble click on the python adsb_map.py? When I do it just opens and closes extremely fast. Do I need a certain python version?

**Comment by furrtek** [comment]
Run it from a terminal, it's probably giving you an error but you can't see it. `python adsb_map.py`.
Python 2.7 is enough, might be broken with Python 3.

**Comment by TeleportingKitten** [comment]
I'm using windows 10, and I've tried python 3 and 2.7 I'm installing kali Linux to see if will be able to build from a Linux system instead of a windows. All let you know if it works.

**Comment by furrtek** [comment]
You shouldn't need Linux for that. Just run python from a cmd prompt and see what it tells you :)

**Comment by TeleportingKitten** [comment]
I'm not sure how to run the file from windows python correctly so I'm using Linux. So I built the map file... but I think the map file is somewhat broken because it shows only 3 locations on the map where the plane is, and the map is half cut from the screen? Maybe my SD card is to old to even run such a big file in real time. But all post a photo here if I can.

**Comment by furrtek** [comment]
I doubt a 64GB (so certainly not too old) would be the cause.
A photo or any error/warning messages would help.

**Comment by Artorios87** [comment]
продавец сказал что поддерживает 128gb!

**Comment by Artorios87** [comment]
отформатировал в fat-32  Thanks

**Comment by Jean-france** [comment]
Hi all,
I have the same problem ; I can't Capture, the hack write a error : **no filesystem**.
I have the Havoc firmware and i wipe my 64 Go SD card, but nothing.
Coulg you help, if you have any idea...
Thanks in advance.
Best regards,
Jean

**Comment by Ahorrorfilm** [comment]
Be sure you put the files from "sdcard" on your..sdcard, but if you've
already did that then you probably have the splash screen issue..so disable
the splash on startup or whatever it's called (sorry I have horrid memory
and currently dont have my hackrf on me) then turn it off and back on and
your files should be there. Also, that was an issue I experienced with
older firmware and haven't experienced it anymore since the newer releases,
so maybe even flashing the latest release would help. Hopefully that helps,
sorry if that's all to ran together...I know sometimes there's a language
barrier here..

**Comment by Jean-france** [comment]
Many thanks for your reply.
"Be sure you put the files from "sdcard" on your..sdcard, ", ? How you do this ? My sdcard is empty, nothing inside....

**Comment by furrtek** [comment]
https://github.com/sharebrained/portapack-hackrf/wiki/General-Use
Format to FAT32, not ExFAT. Copy/paste "sdcard" folder to the root of the sd card.
