### ISSUE TITLE
Compiling a new havoc firmware

### ISSUE THREAD

**Issue by moayadassil** [furrtek/portapack-havoc#258]
Hello.  I made some changes on the firmware havoc but I found a difficulty to compile.  Can you  give me some references or tips for compilations

**Comment by furrtek** [comment]
Hello. Do we have to guess what's going on ? :p
Please provide some details (errors, warnings...)

**Comment by moayadassil** [comment]
i slove it thank you

**Comment by moayadassil** [comment]
thank you
