### ISSUE TITLE
How exactly do I get an SD card working?

### ISSUE THREAD

**Issue by ogdood** [furrtek/portapack-havoc#267]
I have a 128gb micro-SD card in my portapack and Havoc is running just fine. I tried to 'Capture' a frequency and when I pressed that red circle "R", it gives me a red exclamation point inside a triangle and it reads: "no filesystem". My only option at that point is to press "OK".

I put my portapack into DFU mode and on Windows 10, I tried using diskpart to find the partition. When I did a LIST DISK, the SD card in this portapack didn't come up, just my SSD and my backup drive. I double checked that my Windows box recognized the device and it does.

I went through the wiki and I cant find anywhere on how exactly to format an SD card, what file system its using, etc.

Any help would be really appreciated.

Im on Windows 10 but I also have a Macbook Pro and I have a Ubuntu box as well.

Thanks.

**Comment by ogdood** [comment]
Please close this. I used this incredibly new and sophisticated option here on Github named the SEARCH function.

Why am I slow -_-

Solution found, thanks.

(Its FAT or FAT32)

**Comment by DEFCON3187** [comment]
well? Did you resolve the issue?

**Comment by furrtek** [comment]
I'm at a train station right now, those tracks are very inviting.

**Comment by DEFCON3187** [comment]
LOL!!!



Lorenzo Tempany | Managing Director
SHM Projects | 3 Kings Cross Road Potts Point | Sydney  NSW  2010
m: 0404695175  | e: ltempany@shmprojects.com.au  | f: +61 2 80466293
w: www.shmprojects.com.au | abn: 68 419 031
