### ISSUE TITLE
BHT xy/ EP frequency

### ISSUE THREAD

**Issue by nocomp** [furrtek/portapack-havoc#278]
Hi folks.
Do you think it can be possible to add these frequencies in the directory?
What is the frequency rang?
Thx for your help

**Comment by furrtek** [comment]
Hi,
31~32MHz, only works in France. They can be found on publicly available commercial brochures from BHT.

**Comment by nocomp** [comment]
merci beaucoup !!
never heard about this before, is it reguraly sending hand shakes to veryfiy that evrything is up?
thx a lot @furrtek  for your time

**Comment by nocomp** [comment]
damm, not my town :/
https://www.bh-technologies.com/economie-eclairage-public/
