### ISSUE TITLE
clock backup 

### ISSUE THREAD

**Issue by pawel37** [furrtek/portapack-havoc#287]
the clock keeps resetting after i power off is that a software or a hard ware issue.

**Comment by furrtek** [comment]
If you bought a clone Portapack then it's probably a hardware issue. Check the battery voltage.

**Comment by pawel37** [comment]
I have put in a new battery and still no backup.

**Comment by furrtek** [comment]
Where did you get your Portapack ?

**Comment by pawel37** [comment]
EBay

**Comment by furrtek** [comment]
Problem solved.

**Comment by pawel37** [comment]
How did i fix it thanks

**Comment by pawel37** [comment]
Where did i get the real portapack from thanks
