### ISSUE TITLE
TMPS

### ISSUE THREAD

**Issue by pawel37** [furrtek/portapack-havoc#289]
Hello is there away the change the freq on the tmps because the 434 freq im not getting any thing my tpms is on 433.9200 how can u change that or add that in the tpms so i can the freq like in audio thanks.

**Comment by furrtek** [comment]
434 is short for 433.92. Rx is wide enough to catch it even if it's not exactly 433.920000.
PS: It's **TPM**S.

**Comment by pawel37** [comment]
Ok thanks. Mate need a better antenna
