### ISSUE TITLE
POCSAG

### ISSUE THREAD

**Issue by pawel37** [furrtek/portapack-havoc#294]
can u send message to an apollo ala25 r8p8 pager

**Comment by furrtek** [comment]
Maybe. You tried, right ?

**Comment by pawel37** [comment]
hey why has pocsag stopped working tx and cant rx  on ur bin file why is that

**Comment by furrtek** [comment]
No effort to be understood -> no effort to provide help.

**Comment by pawel37** [comment]
Hey did u close it's
