### ISSUE TITLE
Can't get splash screen to close

### ISSUE THREAD

**Issue by mwarchut** [furrtek/portapack-havoc#3]
Hello

Updated to latest version of firmware.  It is setup to show splash screen on boot.  Cannot exit from splash screen.  Is there any way to reverse upgrade or get past splash screen.

**Comment by furrtek** [comment]
Hello,
Sorry for that. I can't build a new binary right now but you can try if you have the setup. I just updated firmware/ui_navigation.cpp

**Comment by mwarchut** [comment]
The issue is resolved now.  Thank you for the excellent work.
