### ISSUE TITLE
the screen portapack not working

### ISSUE THREAD

**Issue by Mars0117** [furrtek/portapack-havoc#308]
Hi!
Earlier i installed the portapack-havoc firmware. 4 day worked. And then I tried SSTV for the first time, pressed "start" and the screen not working.
And i installed the portapack-sharebrained, also not working...
I re-installed the portapack-havoc firmware. I tried with the DFU bootloader but the of no use:

dfu-util --device 1fc9:000c --download hackrf_one_usb.dfu --reset
hackrf_spiflash -w portapack-h1-havoc.bin

also not working...

![photo_2020-02-26_16-37-02](https://user-images.githubusercontent.com/37939002/75360772-94aed780-58b6-11ea-85fb-cb8e0689ed32.jpg)
After connecting USB to a PC or PowerBank the 3V3 and the 1V8 and the RF is lights always ON, USB and TX is always OFF, RX yellow light always blink.

hackrf_info:
hackrf_info version: unknown
libhackrf version: unknown (0.5)
Found HackRF
Index: 0
Serial number: 000000000000000057b068dc25488963
Board ID Number: 2 (HackRF One)
Firmware Version: 2018.01.1 (API:1.02)
Part ID Number: 0xa000cb3c 0x00594766

Thank for your help

**Comment by furrtek** [comment]
Hello,
Chinese clone, doesn't work with the original firmware from Sharebrained -> fault unrelated to firmware. Closing.

**Comment by Mars0117** [comment]
Before the problem the original firmware and havoc worked 4 day.
