### ISSUE TITLE
Sigfox/LoRa

### ISSUE THREAD

**Issue by Nyessss** [furrtek/portapack-havoc#311]
Hi guys, any improvement about this protocols? Should be great to have these on portapack.
Have difficulties for using Tedi/LCR.Pocsag in the cheese and wine country too...
What's the différence beetween green icons, ornage and yellow ones on the Portapack UI ?
Let me know if you're working on it or have difficulties.
Thank you all

**Comment by furrtek** [comment]
#166
#212

**Comment by Nyessss** [comment]
Still trying to make the integration ? or retro consoles projects takes priority ?

**Comment by furrtek** [comment]
I don't want to be alone working on this anymore.
100+ issue tickets, still getting e-mails from clueless people, and barely 10 outside edits to the code.
