### ISSUE TITLE
Error on last step of firmware build

### ISSUE THREAD

**Issue by rockout19** [furrtek/portapack-havoc#314]
I worked through the firmware building steps successfully until the very last command.  When I run the final "make firmware" command, I get "make[5]: arm-none-eabi-gcc: Command not found"

Anyone seen this before?  Screenshot attached.

![image](https://user-images.githubusercontent.com/62040370/76369848-35a78480-62f2-11ea-8061-73c19f651a78.png)

**Comment by x0urc3** [comment]
`arm-none-eabi-gcc` is not available. Try installing it.
