### ISSUE TITLE
Bq24075 bat charge on h1

### ISSUE THREAD

**Issue by antonlalala** [furrtek/portapack-havoc#316]
Hello friends, are there people who soldered bq24075? On h1
![D0D483A1-B784-4786-B377-EF637FABB595](https://user-images.githubusercontent.com/43932931/77107807-4bbfee00-6a32-11ea-8bf1-ca94fedea43e.jpeg)
![9D6A0746-741A-44E8-B11D-028CE11EE9CC](https://user-images.githubusercontent.com/43932931/77107833-51b5cf00-6a32-11ea-85b2-80f9082ff704.jpeg)
  How will it even turn on? by pressing which button? I did not understand.

**Comment by jboone** [comment]
Hi. If you have issues with the hardware design, you should post your issue in the repository where the hardware originated: https://github.com/sharebrained/portapack-hackrf
