### ISSUE TITLE
Is it possible - save jammer freq set

### ISSUE THREAD

**Issue by gh0stshell** [furrtek/portapack-havoc#32]
When choosing a preset or use section 2 and entering a freq when backing out of the app and when returning the settings reset.

I noticed when I flash my settings are still there so I wonder if its possible for this app like it does with the receiver app.

**Comment by furrtek** [comment]
I'm trying to save bytes in the battery-backed RAM (256 bytes max).
Maybe it could save the settings to the SD card instead ?
