### ISSUE TITLE
Why debug app was removed?

### ISSUE THREAD

**Issue by eried** [furrtek/portapack-havoc#325]
Hi, why the debug (free memory, etc) app was removed?

https://github.com/furrtek/portapack-havoc/commit/b29c1d97495b3ceebb237839889dc2dbf22e3aee

**Comment by furrtek** [comment]
Hi. Because it was of no real use to anyone not messing with the code, since it was for... debugging.

**Comment by eried** [comment]
I see. But it shows the available free mem, also the other app that measures the microsd card speed, etc. Those are more useful than the current Notepad for example.

I was wondering while learning about the way apps work (I want to make a "drone finder helper app") thinking as a first step on porting those from sharebrained's repo, but then discovering that they were just commented out.
