### ISSUE TITLE
ABOUT PORTAPACK H2: UNRECOGNIZED USB DEVICE

### ISSUE THREAD

**Issue by SASTREPRIM** [furrtek/portapack-havoc#329]
Hi people!!. Congratulatios for this great web. I just assembled my portapack H2 and I get de firmware from sharebrained (https://github.com/sharebrained/portapack-hackrf/releases/tag/20190405).
I have been watching several tutorials to carry out the firmware installation process so I think that the process has been carried out well.  But I have a problem: 
the device is not recognized. I use Win 7. But 
I have tried it on a windows 10; the problem it is the same. 

Could you help me? Please...
Regards, 
Sastreprim

**Comment by furrtek** [comment]
1) Issue not related to this firmware
2) Question already asked approx 1.5 billion times
3) Shit quality, license infringing hardware
