### ISSUE TITLE
ABOUT THE REASON OF  UNRECOGNIZED DEVICE

### ISSUE THREAD

**Issue by SASTREPRIM** [furrtek/portapack-havoc#330]
Hi again: 
Sorry if my question asked 1,5billion times. Sorry!! 
Shit quality?? I think not. The manufactures of both PCB (HackRF One and Portapack H2 are originals
The soft is original too. 

Could you tell me the possible cause of non-recognition of the device?

Regards,
Sastreprim

**Comment by furrtek** [comment]
Not firmware related. Ask the seller. This is not a forum.
DO NOT open a new issue about this. I hope it's clear this time.
