### ISSUE TITLE
Devices detected: 0 DFU, 0 HackRF ERROR: HackRF not found. Please connect a HackRF One to your computer's USB port. If using a PortaPack, please put it in HackRF mode after connecting it.

### ISSUE THREAD

**Issue by andytang123456789** [furrtek/portapack-havoc#348]
I received the radio through #SDR, but I cannot flash the firmware because the firmware cannot recognize hackrf one, even if I enter hackrf mode

**Comment by Phreak87** [comment]
Have you done the Installation via zadig/urules.dev?
I know this Problem If the Driver was wrong or vbox cannot Import the device.

**Comment by andytang123456789** [comment]
yes  via zadig ,i I received the FM radio through #SDR  on the computer

**Comment by Phreak87** [comment]
Are the drivers installed correctly? 
Zadig winusb or Linux udev.rules?
In vbox you have to auto-mount the dfu-device via the settings

**Comment by Phreak87** [comment]
The dfu is another device. Please Check via the device Manager / zadig again If the dfu Driver is installed

**Comment by andytang123456789** [comment]
I can enter DFU mode and the computer recognizes it

Devices detected: 1 DFU, 0 HackRF
WARNING: One or more DFU devices detected.
Updating from DFU mode is not yet supported.
ERROR: HackRF not found.
Please connect a HackRF One to your computer's USB port.
If using a PortaPack, please put it in HackRF mode after connecting it.

**Comment by eried** [comment]
Go to device manager and replace the driver with the one in /driver/ in the firmware zip

**Comment by andytang123456789** [comment]
sorry , do you have it firmare and driver  ,would send it to my email :fcstrend@gmail.com

**Comment by andytang123456789** [comment]
![image](https://user-images.githubusercontent.com/34892935/80705137-76fd2900-8b18-11ea-91f8-b4ace99c5c73.png)

**Comment by eried** [comment]
Go to device manager and replace the driver with the one in that zip

![image](https://user-images.githubusercontent.com/1091420/80706270-52895880-8ae8-11ea-82d2-b704d0029b5e.png)

If the device is not there, check http://blog.didierstevens.com/2017/09/18/quickpost-gnu-radio-on-windows/

**Comment by andytang123456789** [comment]
i did it but ,it is still  have the problem , maybe the some other problem ,
![image](https://user-images.githubusercontent.com/34892935/80707237-3b645e00-8b1c-11ea-86c5-44fa6d3498aa.png)
![image](https://user-images.githubusercontent.com/34892935/80707312-5505a580-8b1c-11ea-8c0c-1deeeedb874c.png)

**Comment by andytang123456789** [comment]
and did it according this vedio not successful also
https://www.youtube.com/watch?v=5G5blPPIIBo

**Comment by eried** [comment]
Did you installed the driver updating "HackRF One"?

**Comment by eried** [comment]
![image](https://user-images.githubusercontent.com/1091420/80706270-52895880-8ae8-11ea-82d2-b704d0029b5e.png) 

Select `driver/hackrf_one.inf`

**Comment by andytang123456789** [comment]
YES ,I did it ,and My computer says this is the best driver

**Comment by eried** [comment]
> YES ,I did it ,and My computer says this is the best driver

But select `driver/hackrf_one.inf`, not automatic.

**Comment by andytang123456789** [comment]
it is right  ？![image](https://user-images.githubusercontent.com/34892935/80717215-32c75400-8b2b-11ea-900c-402444eb5930.png)

**Comment by andytang123456789** [comment]
sir, problem solved , have to use  old version  
![image](https://user-images.githubusercontent.com/34892935/80717964-1e378b80-8b2c-11ea-98e9-6ac7f3f0cd64.png)

**Comment by andytang123456789** [comment]
thank  you sir , for you support
