### ISSUE TITLE
I would like to have more than 99 lines in /FREQMAN files

### ISSUE THREAD

**Issue by alain00091** [furrtek/portapack-havoc#361]
it is right now limited by the code  in freqman.hpp " #define FREQMAN_MAX_PER_FILE 99" , I changed it to 499 and recompile the code
Scanner is working perfectly but File manager and frequency manager crashes

An example of file is 240 channels of CB (lower/superior channels) 

I just started to learn C++, sorry for that

**Comment by furrtek** [comment]
That's why FREQMAN_MAX_PER_FILE is defined to 99 and not 499 :)
There isn't much RAM to play with.

**Comment by alain00091** [comment]
Yes I understand your answer but for robustness firmware should check if there is enough memory before mem allocation

**Comment by furrtek** [comment]
There's no dynamic memory allocation.
You changed a constant without checking how it was used.

**Comment by alain00091** [comment]
Yes I know it now after I read the code
I made a lot of test with many files and huge files, so it is always possible to crash it even if we use the magic number 99 ...
A better way is to use old style malloc/calloc dynamic allocation, I need to go in deep in the code to check vector allocation, it should be dynamic
