### ISSUE TITLE
is it possible to switch off the portapack by software ?

### ISSUE THREAD

**Issue by alain00091** [furrtek/portapack-havoc#362]
Today I have to disconnect the USB cable and wait ... or disconnect the battery or add a hardware switch to the battery

**Comment by furrtek** [comment]
That's not possible, there's no software controllable switch for that.
Furthermore, internal batteries aren't supported.

**Comment by eried** [comment]
@alain00091 the _illegal clone_ sold in ali (portapack H2) handles on/off/battery charging
