### ISSUE TITLE
Cannot Flash After Last Firmware Update

### ISSUE THREAD

**Issue by gh0stshell** [furrtek/portapack-havoc#38]
After flashing the last version posted I am guessing since hack_rf mode is broken is the reason why I cannot flash the firmware released a few days ago

hackrf_spiflash -w portapack-h1-havoc-03132017.bin
File size 841824 bytes.
hackrf_open() failed: HACKRF_ERROR_NOT_FOUND (-5)

How do I flash the new firmware now that once placed in HACKRF mode like I used to do and then flash no longer works for me.

Anyone else run into this and if so how did you flash?

**Comment by furrtek** [comment]
https://github.com/sharebrained/portapack-hackrf/wiki/Updating%20Firmware
dfu-util before hackrf_spiflash.

**Comment by gh0stshell** [comment]
OK thanks
