### ISSUE TITLE
WFM broken with latest firmware

### ISSUE THREAD

**Issue by dc1rdb** [furrtek/portapack-havoc#42]
Just flashed latest firmware https://github.com/furrtek/portapack-havoc/commit/b61869f1c04eaa43566648a917c5640f2af2f830 and did some quick checks. WFM mode in FM broadcast band seems to be broken, no demodulation.
AM tested in short wave and aviation bands, working fine here.

**Comment by djpadbit** [comment]
Yea can comfirm, its the same issue as last time https://github.com/furrtek/portapack-havoc/issues/7

**Comment by dc1rdb** [comment]
HackRF CPLD check reports ok this time, though.

**Comment by djpadbit** [comment]
this commit seems to distort WFM https://github.com/sharebrained/portapack-hackrf/commit/05eb694c0a9d29e3098e396b53a7e0fb05fe9b93 and it isn't fixed yet.

**Comment by furrtek** [comment]
Thanks for spotting the commit. I will look into it shortly and revert back to the SIMD macros if I can't understand what's going on.

**Comment by furrtek** [comment]
Reverted to the SIMD macros in a053c0e, no idea why it does that.

**Comment by dc1rdb** [comment]
Latest pre-built version https://github.com/furrtek/portapack-havoc/blob/master/firmware/portapack-h1-havoc.bin does not seem to include commit https://github.com/furrtek/portapack-havoc/commit/a053c0e234ee3373248607864ddf78ae11d10a18, still shows https://github.com/furrtek/portapack-havoc/commit/fbc054ca75d8784799dec4d10562efdf81bf7cd5 on the about screen.

**Comment by mullwar** [comment]
Does this resolves weird signal mirroring bug?
