### ISSUE TITLE
Hackrf USB mode not works

### ISSUE THREAD

**Issue by Sasul** [furrtek/portapack-havoc#43]
Since the last update the hackrf USB mode no longer works. How can I solve the problem under windows and install a new firmware.

**Comment by furrtek** [comment]
Did you try to just re-flash the original PP firmware as described here:
https://github.com/sharebrained/portapack-hackrf/wiki/Updating%20Firmware%20Windows
?

**Comment by Sasul** [comment]
Unfortunately this is not possible. Because this must be the hackrf in the USB mode. Exactly this is no more.

**Comment by furrtek** [comment]
DFU is a hardware feature, not software. If the hardware isn't damaged, DFU mode should work.
Use dfu-util and upload the original firmware.

**Comment by Sasul** [comment]
Thank you, your tip with the DFU Mode has worked. It is all very well again.
