### ISSUE TITLE
RDS Radiotext is not recognized by car radio

### ISSUE THREAD

**Issue by furrtek** [furrtek/portapack-havoc#44]
Windytan's Redsea shows the raw groups but doesn't recognize them as valid Radiotext.
Basic car radio ignores them (while being compatible with Radiotext, tested).

**Comment by F4GEV** [comment]
Same issue in my car.
middle level GPS embedded car radio.

**Comment by furrtek** [comment]
Tested on car radio and portable receiver with RDS functionality, works now :)
