### ISSUE TITLE
Compilation Issue

### ISSUE THREAD

**Issue by F4GEV** [furrtek/portapack-havoc#45]
I have errors when i compile last Havoc firmware.

----

[ 96%] Generating baseband_tpms.bin, baseband_tpms.img
[ 96%] Generating baseband_wideband_spectrum.bin, baseband_wideband_spectrum.img
[ 96%] Generating baseband_wfm_audio.bin, baseband_wfm_audio.img
[ 97%] Generating baseband.img
cat: hackrf.img: No such file or directory
cat: terminator.img: No such file or directory
make[3]: *** [firmware/baseband/baseband.img] Error 1
make[3]: *** Deleting file `firmware/baseband/baseband.img'
make[2]: *** [firmware/baseband/CMakeFiles/baseband.dir/all] Error 2
make[1]: *** [firmware/CMakeFiles/firmware.dir/rule] Error 2
make: *** [firmware] Error 2

**Comment by furrtek** [comment]
It's amazing how I'm able to make problems occure in a loop.
While I find a real solution, you can copy hackrf.img and terminator.img from Sharebrained's repo.

**Comment by F4GEV** [comment]
Many thanks,
works with workaround !!

**Comment by furrtek** [comment]
Added required files in 62b9094, even if the makefile should generate them. Workaround for now...

**Comment by F4GEV** [comment]
Sorry issue is present with this update
