### ISSUE TITLE
Code transmitter / TEDI - LCR : SCAN can't Abort

### ISSUE THREAD

**Issue by F4GEV** [furrtek/portapack-havoc#47]
In this menu when you lauch a SCAN , the abort button is without effect.
Must RESET for stop the procedure.

**Comment by furrtek** [comment]
The button does work but tx is stopped only once all repeats of a same message are done.
Stops and shows "Abort @****". Changing code so that tx is stopped immediately.

**Comment by furrtek** [comment]
Fixed in 62b9094.
