### ISSUE TITLE
Setup > UI > Show splash not selectable

### ISSUE THREAD

**Issue by dc1rdb** [furrtek/portapack-havoc#5]
After flashing latest firmware f399548, the show splash option in UI setup is no longer selectable.

Thanks so much for this great firmware, it is getting better and more mischievous with every commit! Really appreciate your hard work.

**Comment by furrtek** [comment]
Thanks for the kind words and the report.
It's an issue with the next focusable element guessing, you can still choose the option by using the touchscreen. I'll get to it in a few hours.

**Comment by dc1rdb** [comment]
Touchscreen confirmed. Didn't even think about trying it. My fault. Thanks for your quick response.

**Comment by furrtek** [comment]
Moved widgets so it works again, will be fixed in next release.

**Comment by dc1rdb** [comment]
Works like a charm - perfect, thanks!
