### ISSUE TITLE
POCSAG TX exit

### ISSUE THREAD

**Issue by KC5CQW** [furrtek/portapack-havoc#53]
Curser does not return to the back arrow. Must cycle the power and reboot to exit POCSAG TX.

**Comment by furrtek** [comment]
I'm not able to reproduce the problem. Are you pressing left from somewhere special in the POCSAG TX screen ?

**Comment by F4GEV** [comment]
try to click in the same time LEFT and UP when you are in the bitrate field.
73
F4GEV

**Comment by furrtek** [comment]
Ok, got the problem when having the frequency field focused.
The back button should now always be in reach with the left key (commit eff9627).
