### ISSUE TITLE
POCSAG : Ignor address does'nt work

### ISSUE THREAD

**Issue by F4GEV** [furrtek/portapack-havoc#54]
When selected with a  test address, the consol display messages => filter does not work.

*Désolé furrtek, une belle release quand même *

**Comment by furrtek** [comment]
Oops, what was I thinking ? It was only filtering "address only" messages to avoid duplicate notifications in the console. Now, nothing is displayed and logged at all for the ignored address (commit 40b49e2).

New messages starts with a green header (Time, baudrate, address, function).
Continued messages are in regular white text. The line breaks should be OK on the console.

**Comment by F4GEV** [comment]
Works, thanks Monsieur
so in my town the Test Add is 1111107 is it possible to save the last enterred Add in RAM (battery saved" ?

**Comment by furrtek** [comment]
Added auto save in 90feadd

**Comment by F4GEV** [comment]
all works fine 
Good job
