### ISSUE TITLE
Recievers audio causes portapack to go nonresponsive

### ISSUE THREAD

**Issue by BustedSec** [furrtek/portapack-havoc#56]
In this mode I can't change the frequency and all buttons go unresponsive. Can't exit it. It says RSSI in red underneath

**Comment by furrtek** [comment]
Main menu -> Receivers -> Audio, and it freezes right away ?

**Comment by BustedSec** [comment]
yup - no waterfall and everything unresponsive until reboot. I just pushed the older commit - went back 2 days - and that version of the precompiled bin works

**Comment by furrtek** [comment]
Just updated the binary, give it a try.
