### ISSUE TITLE
AIS does not work after update

### ISSUE THREAD

**Issue by F4GEV** [furrtek/portapack-havoc#58]
No frames decoded !!
Have many boats near my house.

**Comment by furrtek** [comment]
Will try it out this week. Didn't touch the AIS code, wondering what I broke again...

**Comment by F4GEV** [comment]
you don't have modify modem files ?
may be this way ?

**Comment by furrtek** [comment]
I don't think AIS is AFSK :)

**Comment by F4GEV** [comment]
No, i will think this touch any modulations.
It was not :-)

Good luck !

**Comment by F4GEV** [comment]
works  now with  790ec34 !!
