### ISSUE TITLE
Compile issue on macOS

### ISSUE THREAD

**Issue by djjerdog** [furrtek/portapack-havoc#63]
$ sudo make firmware 
[  0%] Building C object bootstrap/CMakeFiles/bootstrap.elf.dir/bootstrap.o
clang: error: unknown argument: '-mno-thumb-interwork'
clang: warning: optimization flag '-falign-functions=16' is not supported [-Wignored-optimization-argument]
make[3]: *** [bootstrap/CMakeFiles/bootstrap.elf.dir/bootstrap.o] Error 1
make[2]: *** [bootstrap/CMakeFiles/bootstrap.elf.dir/all] Error 2
make[1]: *** [CMakeFiles/firmware.dir/rule] Error 2
make: *** [firmware] Error 2

**Comment by furrtek** [comment]
You need gcc-arm: https://github.com/sharebrained/portapack-hackrf/wiki/Building-Firmware
