### ISSUE TITLE
Invisible saved frequency name

### ISSUE THREAD

**Issue by Pine-d-Huitre** [furrtek/portapack-havoc#64]
If I try to save a frequency, I can only set the first letter of the name, the others are invisible.

**Comment by Pine-d-Huitre** [comment]
This is a write problem. If you manually edit freqman.txt, the frquency manager is able to show full names.
So the frequency manager is only able to write the first letter when saving a station.

**Comment by furrtek** [comment]
Probably a shameful bug about std::string and char* in ui_alphanum.cpp. I'll check it out tonight.

**Comment by furrtek** [comment]
Should be fixed in 042d271, please close if you can confirm.
