### ISSUE TITLE
How to use frequency directory ?

### ISSUE THREAD

**Issue by F4GEV** [furrtek/portapack-havoc#67]
Your add some txt files in freqman directory but how use them ?

laurent

**Comment by furrtek** [comment]
The frequency manager can't use them for now. They will be loaded automatically.

**Comment by F4GEV** [comment]
Thank for this answer, i don't see where ! ??

**Comment by furrtek** [comment]
What are you trying to find ?

**Comment by F4GEV** [comment]
nothing, i like know how it's work and why :-) just curiosity
i'm amateur radio, and some frequencies are unknow for me. I want know how and by what application they are used.
Just for example : MURS.TXT ????
Thanks for all
Laurent

**Comment by furrtek** [comment]
https://en.wikipedia.org/wiki/Multi-Use_Radio_Service :)

**Comment by F4GEV** [comment]
OK thanks :-)
