### ISSUE TITLE
mic issue

### ISSUE THREAD

**Issue by ImDroided** [furrtek/portapack-havoc#76]
Hi I have just received my portapack the new all black model and I have tried 10 different mics and none of them work with the mic transmit. I hear the roger beep on my radio but no audio. I have tried all types of mics from ear buds to my gaming headsets and I can hear just fine with them just no mic. I have even tried the samsung ear buds that came with my old phone which says is compatible but no luck. Am I using a wrong setting here or is this a bug? My buddy seems to be having the same issue.

**Comment by jboone** [comment]
I'm curious what is the small date code on the front of your PortaPack -- 20170522 or 20150901?

        - Jared

**Comment by ImDroided** [comment]
20170522. We just got these the other day.

**Comment by ImDroided** [comment]
This issue still exists any suggestions?

**Comment by ImDroided** [comment]
This is now working please close this issue.
