### ISSUE TITLE
Replay option freezes unit

### ISSUE THREAD

**Issue by kpeezy707** [furrtek/portapack-havoc#79]
Not sure if im doing something wrong but when i select replay option the unit just freezes. Do i need capture files on the SD card for the option to work? Cant find anything about it on the wiki.

Thank you
kpeezy

**Comment by kpeezy707** [comment]
Figured it out sorry about posting this, just needed an actual capture file.

**Comment by furrtek** [comment]
Replay is very buggy, the clue is in the app's "title bar". Title bar which indeed doesn't show up if an I/Q file isn't found on the SD card. This needs some work.

**Comment by furrtek** [comment]
The replay app now shows an error when no files are found.
