### ISSUE TITLE
Audio TX Soundboard don't work 

### ISSUE THREAD

**Issue by Giorgiofox** [furrtek/portapack-havoc#8]
Hi, 
with latest two release the Soundboard hangup when selected. 

Now what I do to transmit Imperial March?! ;)

PS, feature request: SSB mode transmit for sound board. 

thanks
Giorgio

**Comment by furrtek** [comment]
Hello,
There was a long filename issue, it's now working on my side. Please let me know if it solved the problem for you.
Will look into SSB transmit :)

Thanks.

**Comment by Giorgiofox** [comment]
Now the Soundboard not hangup when selected, it load the wav selection screen, but If I select a wav it not transmit. The TX led don't turn on.

**Comment by furrtek** [comment]
Should be good now. I'm good at fixing half of a bug...

**Comment by Giorgiofox** [comment]
It's very good now, perfect. Thank you. 
Now I need to go to transmit Imperial March.
