### ISSUE TITLE
Play dead mode

### ISSUE THREAD

**Issue by Redouan29** [furrtek/portapack-havoc#80]
Is it me or is the play dead mode broken?
If I set in the Setup/UI the "login with play dead" on, it is still always turning on normally (on a new power cycle).

**Comment by djpadbit** [comment]
I don't think the play dead mode is broken, it just has been disabled (see commit https://github.com/furrtek/portapack-havoc/commit/f6b02c31b5d7c298ec71a3049f97bdf1cc906d00 ). It should work again if you uncomment the code that has been commented out. But then again I might be wrong, hope it helps anyways

**Comment by furrtek** [comment]
It was indeed disabled because it kept causing problems after updates. I'll get it working correctly one day.

**Comment by Redouan29** [comment]
Ok clear for me. Thanks for the answers!

**Comment by h4waii** [comment]
Any update on having this enabled again?
