### ISSUE TITLE
Loading pre-built binary successful, but only get blank screen on PortaPack

### ISSUE THREAD

**Issue by b10w** [furrtek/portapack-havoc#82]
Attempting to load havoc for the first time.

I'm able to successfully run dfu-ultil and flash the pre-compiled havoc binary. However, after power cycling the unit I just get a blank screen. Power light along with lights 3, 4, and 5 (green, amber, red) are illuminated.

**Comment by furrtek** [comment]
The binary isn't up to date. Try building the source yourself or wait a bit until I update the binary.
