### ISSUE TITLE
Frequency Manager not working

### ISSUE THREAD

**Issue by ereuter** [furrtek/portapack-havoc#83]
When I go to Frequency Manager in Utilities, the device freezes.  If I try to save a frequency elsewhere, I get a "No database files" screen with exclamation point.  If I try to load, it freezes the device.  

I tried touching FREQMAN.TXT on the SD card, and no change.  

Hardware is 20170522 version.

**Comment by furrtek** [comment]
There's no FREQMAN.TXT file anymore, see sdcard/FREQMAN/ in the repo.

**Comment by ereuter** [comment]
Thanks. I was going by the wiki. In any case, from a freshly formatted card, what do I need to do to get the frequency manager running?  Copy the files from the repo to the root?2

**Comment by ImDroided** [comment]
copy the sdcard folder to a sd card and everything works.

**Comment by ereuter** [comment]
Thanks.  It's working now.  If I missed that in the documentation, I apologize.

**Comment by furrtek** [comment]
The wiki wasn't updated, it will be soon :)
