### ISSUE TITLE
Jamming bandwidth too large

### ISSUE THREAD

**Issue by tit0n** [furrtek/portapack-havoc#9]
I am getting the error message "Jamming bandwidth too large" when trying the default settings (for example DECT).

Also for some reason, I am unable to change the frequencies using the UI.

**Comment by gh0stshell** [comment]
I tried some of the wifi ones and got the same thing

**Comment by gh0stshell** [comment]
Also should we be able to set freq? Or is it only with the presets?

**Comment by furrtek** [comment]
I increased the max range from 4.5M to 24M, all presets should be able to run now.
Using the min/max buttons should now refresh the values correctly.

**Comment by tit0n** [comment]
Thanks. All preset work now. 
We can also change the min/max values for Range1 now, but changing values for Range2 and Range3 doesn't work.

**Comment by gh0stshell** [comment]
Flashed the new firmware, I can confirm default ranges work and can change only the first range, whether I leave 2 and 3 checked or unchecked it never saves the freq entered.

**Comment by furrtek** [comment]
Bad array index, all buttons should work now.

**Comment by tit0n** [comment]
Resolved. Thanks.
