### ISSUE TITLE
ADS-B RX Hits & Time invisible

### ISSUE THREAD

**Issue by F4GEV** [furrtek/portapack-havoc#90]
when décoding, ICAO and Callsign are visible but Hit and Time is written in black
The text is visible when i select the text (black on white background)

![scr_0039](https://user-images.githubusercontent.com/22217239/29434403-255e1a70-83a3-11e7-9b72-584961c60d0d.PNG)

**Comment by furrtek** [comment]
Fixed in 3aae3339746e630058c3efd49fe64e1af84b3cf2.
