### ISSUE TITLE
ABS-B - Info panel zeroed out

### ISSUE THREAD

**Issue by kpeezy707** [furrtek/portapack-havoc#92]
If you select a plane with no call sign the info panel is zeroed out

![20170825_110531](https://user-images.githubusercontent.com/25161492/29726711-b1f675d0-8985-11e7-8a48-05c29db50b5f.jpg)

**Comment by furrtek** [comment]
That's normal, it shows the last received position frames for debug. No crosshair icon means no position received. I'll make it clearer in a future update :)

**Comment by kpeezy707** [comment]
Sweet! Thanks man, love it

**Comment by furrtek** [comment]
Removed in fa519bba63d13632613a0bb63e61fed4ebabe1a3.
