### ISSUE TITLE
EPAR/XYLOS

### ISSUE THREAD

**Issue by djecom1** [furrtek/portapack-havoc#95]
D'après ce que j'ai compris, Xylos c'est du CCIR alors que EPAR est du FSK.
Hors sur la page Xylos/EPAR, quelque soit le mode choisi, j'ai une émission CCIR.
Est-ce un bug ou ai-je mal compris le fonctionnement?
Merci,
Jérôme, F4GMU

**Comment by furrtek** [comment]
C'est un beau bug ! Je m'y met.

**Comment by furrtek** [comment]
Fixed in a6d2b766f474e41a43f1a509827631373d9fc3a6.

**Comment by djecom1** [comment]
Merci !
